name: Rust-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pysocks
    - name: get socks5-udpchk
      uses: wei/wget@v1
      with:
        args: -O udp.py https://raw.githubusercontent.com/semigodking/socks5chk/master/udpchk.py
    - name: Check socks5
      run: |
        ls -l
        cargo run &
        sleep 3
        python udp.py -p 127.0.0.1 --port 8080

